version: '3.1'
services:
    webserver:
        image: nodetest
        restart: always
        ports: 
            - 6200:3000
        networks:
            - myapp-network    
        depends_on:
            - db
    db:
        image: mcr.microsoft.com/azure-sql-edge:latest
        restart: always
        environment:
            ACCEPT_EULA : true
            MSSQL_SA_PASSWORD: tger-1962
        ports:
            - 1456:1433
        networks:
            - myapp-network  
networks:
    myapp-network:
        driver: bridge  